DECLARE
  V_ID_SISTEMA    TB_SISTEMA.ID_SISTEMA%TYPE   := ACCESSCONTROL.SEQ_SISTEMA.NEXTVAL;
  
  --Relatorio Gerencial Filas Emissor
  V_ID_OPER_E     TB_OPERACAO.ID_OPERACAO%TYPE := ACCESSCONTROL.SEQ_OPERACAO.NEXTVAL;
  V_DS_OPER_E     TB_OPERACAO.DESCRICAO%TYPE   := 'Rel. Gerencial Emissor'; --Nome da Operação
  V_KEY_OPER_E    TB_OPERACAO.CHAVE%TYPE       := 'dxcrel.ger.filas.emissor';
  V_ID_PERF_E     TB_PERFIL.ID_PERFIL%TYPE     := ACCESSCONTROL.SEQ_PERFIL.NEXTVAL;
  V_DS_PERF_E     TB_PERFIL.DESCRICAO%TYPE     := 'DXC - Relatorios-Rel. Gerencial Emissor'; --Nome do Perfil
  V_KEY_PERF_E    TB_PERFIL.CHAVE%TYPE         := ACCESSCONTROL.PKG_ACCESSCONTROL_SOAP.fnGenerateKey;
  
  --Relatorio Gerencial Filas Acquirer
  V_ID_OPER_A     TB_OPERACAO.ID_OPERACAO%TYPE := ACCESSCONTROL.SEQ_OPERACAO.NEXTVAL;
  V_DS_OPER_A     TB_OPERACAO.DESCRICAO%TYPE   := 'Rel. Gerencial Acquirer'; --Nome da Operação
  V_KEY_OPER_A    TB_OPERACAO.CHAVE%TYPE       := 'dxcrel.ger.filas.acquirer';
  V_ID_PERF_A     TB_PERFIL.ID_PERFIL%TYPE     := ACCESSCONTROL.SEQ_PERFIL.NEXTVAL;
  V_DS_PERF_A     TB_PERFIL.DESCRICAO%TYPE     := 'DXC - Relatorios-Rel. Gerencial Acquirer'; --Nome do Perfil
  V_KEY_PERF_A    TB_PERFIL.CHAVE%TYPE         := ACCESSCONTROL.PKG_ACCESSCONTROL_SOAP.fnGenerateKey;  

BEGIN
  -- Obtendo o ID do sistema DXL RELATORIOS
  SELECT ID_SISTEMA INTO V_ID_SISTEMA FROM ACCESSCONTROL.TB_SISTEMA where SYSTEM_KEY = 'CMSISSUERDXCRELATORIOS';

  --Relatorio Gerencial Filas Emissor
  INSERT INTO ACCESSCONTROL.TB_OPERACAO (ID_OPERACAO, DESCRICAO, CHAVE, ID_SISTEMA) VALUES (V_ID_OPER_E, V_DS_OPER_E, V_KEY_OPER_E, V_ID_SISTEMA);

  INSERT INTO ACCESSCONTROL.TB_PERFIL (ID_PERFIL, DESCRICAO, ATIVO, CHAVE) VALUES (V_ID_PERF_E, V_DS_PERF_E, 1, V_KEY_PERF_E);
  
  INSERT INTO ACCESSCONTROL.TB_PERFIL_OPERACAO (ID_PERFIL, ID_OPERACAO) VALUES (V_ID_PERF_E, V_ID_OPER_E);
  
  --Relatorio Gerencial Filas Acquirer
  INSERT INTO ACCESSCONTROL.TB_OPERACAO (ID_OPERACAO, DESCRICAO, CHAVE, ID_SISTEMA) VALUES (V_ID_OPER_A, V_DS_OPER_A, V_KEY_OPER_A, V_ID_SISTEMA);

  INSERT INTO ACCESSCONTROL.TB_PERFIL (ID_PERFIL, DESCRICAO, ATIVO, CHAVE) VALUES (V_ID_PERF_A, V_DS_PERF_A, 1, V_KEY_PERF_A);

  INSERT INTO ACCESSCONTROL.TB_PERFIL_OPERACAO (ID_PERFIL, ID_OPERACAO) VALUES (V_ID_PERF_A, V_ID_OPER_A);  
  COMMIT;
END;
/