CREATE TABLE DXC_RELATORIOS (
    ID_REL                  NUMBER(18) NOT NULL,
    NM_ARQUIVO              VARCHAR2(100) NOT NULL,
    ARQUIVO                 BLOB,
    CONSTRAINT PK_DXC_RELATORIOS PRIMARY KEY (ID_REL)
);

COMMENT ON TABLE DXC_RELATORIOS             IS 'Tabela DXC para salvar relatorios (arquivos)';
COMMENT ON COLUMN DXC_RELATORIOS.ARQUIVO    IS 'Arquivo do relatorio';

CREATE SEQUENCE SEQ_DXC_RELATORIOS;